# Generated by Django 2.1 on 2019-07-23 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='createtime',
            field=models.TimeField(default=datetime.datetime(2019, 7, 23, 20, 19, 42, 597803)),
        ),
    ]
