# Generated by Django 2.1 on 2019-07-23 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_blogcontent_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 20, 27, 0, 748870)),
        ),
    ]
