# Generated by Django 2.1 on 2019-07-23 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190723_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='lasttime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 20, 49, 51, 194221)),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 20, 49, 51, 194196)),
        ),
    ]
